-- Topic:  SQL SELECT with WHERE and LIKE
-- Marks:  4
--
-- A library stores book details in a database table called TblBooks.
--
-- TblBooks
-- +--------+-----------------------------+----------+-------+
-- | BookID | Title                       | Author   | Price |
-- +--------+-----------------------------+----------+-------+
-- | 1      | Python Programming           | A. Smith | 9.99  |
-- | 2      | Learn Python Fast            | B. Jones | 7.50  |
-- | 3      | Database Design             | C. Patel | 12.00 |
-- | 4      | Python for Data Science     | D. Lee   | 14.99 |
-- | 5      | Introduction to Algorithms  | E. Brown | 18.00 |
-- +--------+-----------------------------+----------+-------+
--
-- Write a SELECT statement to return only the Title and Author
-- from TblBooks where the Title contains the word "Python".
--
-- Expected output:
--   Python Programming      | A. Smith
--   Learn Python Fast       | B. Jones
--   Python for Data Science | D. Lee

-- Write your SQL query below:
